env:
  - name: 'PYTHON_PATH'
    value: '.venv/bin/python3'
  - name: 'DATABRICKS_HOST'
    value: 'https://fe-vm-lakemeter.cloud.databricks.com'
  - name: 'MLFLOW_TRACKING_URI'
    value: 'databricks'
  - name: 'MLFLOW_REGISTRY_URI'
    value: 'databricks-uc'
  - name: 'MLFLOW_EXPERIMENT_ID'
    value: '1596794712816475'
  - name: 'OPENAI_BASE_URL'
    value: 'https://fe-vm-lakemeter.cloud.databricks.com/serving-endpoints'
  - name: 'CATALOG'
    value: 'lakemeter_catalog'
  - name: 'SCHEMA'
    value: 'lakemeter'
  - name: 'DATABRICKS_TOKEN'
    valueFrom: secret
  - name: 'OPENAI_MODEL'
    value: 'ka-5cb2e157-endpoint'
  - name: 'USE_RESPONSES_API'
    value: true