/**
 * Dropdown options for table columns
 */

export const workloadOptions = [
  "ingestion_connect",
  "sql_analytics",
  "interactive_compute",
];

export const skuOptions = [
  { value: "ALL_PURPOSE_COMPUTE", label: "All Purpose Compute" },
  { value: "ALL_PURPOSE_COMPUTE_(DLT)", label: "All Purpose Compute (dlt)" },
  { value: "ALL_PURPOSE_COMPUTE_(PHOTON)", label: "All Purpose Compute (photon)" },
  { value: "ALL_PURPOSE_SERVERLESS_COMPUTE", label: "All Purpose Serverless Compute" },
  { value: "ANTHROPIC_MODEL_SERVING", label: "Anthropic Model Serving" },
  { value: "CLEAN_ROOMS_COLLABORATOR", label: "Clean Rooms Collaborator" },
  { value: "DATABASE_SERVERLESS_COMPUTE", label: "Database Serverless Compute" },
  { value: "DATABRICKS_STORAGE", label: "Databricks Storage" },
  { value: "DATABRICKS_STORAGE_GB", label: "Databricks Storage Gb" },
  { value: "DATABRICKS_STORAGE_TIER1REQUESTS", label: "Databricks Storage Tier1requests" },
  { value: "DATABRICKS_STORAGE_TIER2REQUESTS", label: "Databricks Storage Tier2requests" },
  { value: "DLT_ADVANCED_COMPUTE", label: "Dlt Advanced Compute" },
  { value: "DLT_ADVANCED_COMPUTE_(PHOTON)", label: "Dlt Advanced Compute (photon)" },
  { value: "DLT_CORE_COMPUTE", label: "Dlt Core Compute" },
  { value: "DLT_CORE_COMPUTE_(PHOTON)", label: "Dlt Core Compute (photon)" },
  { value: "DLT_PRO_COMPUTE", label: "Dlt Pro Compute" },
  { value: "DLT_PRO_COMPUTE_(PHOTON)", label: "Dlt Pro Compute (photon)" },
  { value: "GEMINI_MODEL_SERVING", label: "Gemini Model Serving" },
  { value: "JOBS_COMPUTE", label: "Jobs Compute" },
  { value: "JOBS_COMPUTE_(PHOTON)", label: "Jobs Compute (photon)" },
  { value: "JOBS_LIGHT_COMPUTE", label: "Jobs Light Compute" },
  { value: "JOBS_SERVERLESS_COMPUTE", label: "Jobs Serverless Compute" },
  { value: "MODEL_TRAINING", label: "Model Training" },
  { value: "MODEL_TRAINING_HERO_RESERVATION", label: "Model Training Hero Reservation" },
  { value: "MODEL_TRAINING_IN_CUSTOMER_TENANCY", label: "Model Training In Customer Tenancy" },
  { value: "MODEL_TRAINING_ON_DEMAND", label: "Model Training On Demand" },
  { value: "MODEL_TRAINING_RESERVATION", label: "Model Training Reservation" },
  { value: "MODEL_TRAINING_SERVERLESS_GPU_COMPUTE_PROVISIONED_CAPACITY", label: "Model Training Serverless Gpu Compute Provisioned Capacity" },
  { value: "OPENAI_MODEL_SERVING", label: "Openai Model Serving" },
  { value: "SERVERLESS_REAL_TIME_INFERENCE", label: "Serverless Real Time Inference" },
  { value: "SERVERLESS_REAL_TIME_INFERENCE_LAUNCH", label: "Serverless Real Time Inference Launch" },
  { value: "SERVERLESS_SQL_COMPUTE", label: "Serverless Sql Compute" },
  { value: "SQL_COMPUTE", label: "Sql Compute" },
  { value: "SQL_PRO_COMPUTE", label: "Sql Pro Compute" }
];

export const instanceOptions = [
  "c6id.12xlarge",
  "c6id.16xlarge",
  "c6id.24xlarge",
  "c6id.2xlarge",
  "c6id.32xlarge",
  "c6id.4xlarge",
  "c6id.8xlarge",
  "c6id.xlarge",
  "i3.2xlarge",
  "i3.4xlarge",
  "i3en.12xlarge",
  "i3en.24xlarge",
  "i3en.2xlarge",
  "i3en.3xlarge",
  "i3en.6xlarge",
  "i3en.large",
  "i3en.xlarge",
  "i4i.16xlarge",
  "i4i.2xlarge",
  "i4i.32xlarge",
  "i4i.4xlarge",
  "i4i.8xlarge",
  "i4i.large",
  "i4i.xlarge",
  "m5d.12xlarge",
  "m5d.16xlarge",
  "m5d.24xlarge",
  "m5d.2xlarge",
  "m5d.4xlarge",
  "m5d.8xlarge",
  "m5d.large",
  "m5d.xlarge",
  "m6gd.12xlarge",
  "m6gd.16xlarge",
  "m6gd.2xlarge",
  "m6gd.4xlarge",
  "m6gd.8xlarge",
  "m6gd.large",
  "m6gd.xlarge",
  "m6id.12xlarge",
  "m6id.16xlarge",
  "m6id.24xlarge",
  "m6id.2xlarge",
  "m6id.32xlarge",
  "m6id.4xlarge",
  "m6id.8xlarge",
  "m6id.large",
  "m6id.xlarge",
  "m6idn.12xlarge",
  "m6idn.16xlarge",
  "m6idn.24xlarge",
  "m6idn.2xlarge",
  "m6idn.32xlarge",
  "m6idn.4xlarge",
  "m6idn.8xlarge",
  "m6idn.large",
  "m6idn.xlarge",
  "m7gd.12xlarge",
  "m7gd.16xlarge",
  "m7gd.2xlarge",
  "m7gd.4xlarge",
  "m7gd.8xlarge",
  "m7gd.large",
  "m7gd.xlarge",
  "m7i.12xlarge",
  "m7i.16xlarge",
  "m7i.24xlarge",
  "m7i.2xlarge",
  "m7i.48xlarge",
  "m7i.4xlarge",
  "m7i.8xlarge",
  "m7i.large",
  "m7i.metal-24xl",
  "m7i.metal-48xl",
  "m7i.xlarge",
  "r5d.12xlarge",
  "r5d.16xlarge",
  "r5d.24xlarge",
  "r5d.2xlarge",
  "r5d.4xlarge",
  "r5d.8xlarge",
  "r5d.large",
  "r5d.xlarge",
  "r5dn.12xlarge",
  "r5dn.16xlarge",
  "r5dn.24xlarge",
  "r5dn.2xlarge",
  "r5dn.4xlarge",
  "r5dn.8xlarge",
  "r5dn.large",
  "r5dn.xlarge",
  "r6gd.12xlarge",
  "r6gd.16xlarge",
  "r6gd.2xlarge",
  "r6gd.4xlarge",
  "r6gd.8xlarge",
  "r6gd.large",
  "r6gd.xlarge",
  "r6i.12xlarge",
  "r6i.16xlarge",
  "r6i.24xlarge",
  "r6i.2xlarge",
  "r6i.32xlarge",
  "r6i.4xlarge",
  "r6i.8xlarge",
  "r6i.large",
  "r6i.xlarge",
  "r6id.12xlarge",
  "r6id.16xlarge",
  "r6id.24xlarge",
  "r6id.2xlarge",
  "r6id.32xlarge",
  "r6id.4xlarge",
  "r6id.8xlarge",
  "r6id.large",
  "r6id.xlarge",
  "r6idn.12xlarge",
  "r6idn.16xlarge",
  "r6idn.24xlarge",
  "r6idn.2xlarge",
  "r6idn.32xlarge",
  "r6idn.4xlarge",
  "r6idn.8xlarge",
  "r6idn.large",
  "r6idn.xlarge",
  "r7gd.12xlarge",
  "r7gd.16xlarge",
  "r7gd.2xlarge",
  "r7gd.4xlarge",
  "r7gd.8xlarge",
  "r7gd.large",
  "r7gd.xlarge",
  "r7i.12xlarge",
  "r7i.16xlarge",
  "r7i.24xlarge",
  "r7i.2xlarge",
  "r7i.48xlarge",
  "r7i.4xlarge",
  "r7i.8xlarge",
  "r7i.large",
  "r7i.metal-24xl",
  "r7i.metal-48xl",
  "r7i.xlarge",
  "2X-Small",
  "X-Small",
  "Small",
  "Medium",
  "Large",
  "X-Large",
  "2X-Large",
  "3X-Large",
  "4X-Large"
];

export const workerCountOptions = Array.from({ length: 20 }, (_, i) => String(i + 1));
