"""Regression tests for applying AI-generated estimates."""

from types import SimpleNamespace
from uuid import uuid4

import pytest
from fastapi import FastAPI, HTTPException
from fastapi.testclient import TestClient

from app.auth.databricks_auth import get_current_user
from app.database import get_db
from app.models import Estimate, LineItem
from app.routes import chat as chat_routes


class FakeSession:
    """Small transaction-aware session used by the route tests."""

    def __init__(self):
        self.added = []
        self.commits = 0
        self.rollbacks = 0

    def add(self, record):
        self.added.append(record)

    def flush(self):
        for record in self.added:
            if isinstance(record, Estimate) and record.estimate_id is None:
                record.estimate_id = uuid4()

    def commit(self):
        self.commits += 1

    def rollback(self):
        self.rollbacks += 1


class FakeAgent:
    def __init__(self, estimate, workloads):
        self.current_estimate = estimate
        self.proposed_workloads = workloads
        self.reset_called = False

    def reset(self):
        self.reset_called = True


@pytest.fixture(autouse=True)
def clear_conversations():
    chat_routes._conversation_agents.clear()
    yield
    chat_routes._conversation_agents.clear()


def build_client(db, current_user=None, auth_error=None):
    app = FastAPI()
    app.include_router(chat_routes.router, prefix="/api/v1")
    app.dependency_overrides[get_db] = lambda: db

    if auth_error:
        def reject_user():
            raise auth_error

        app.dependency_overrides[get_current_user] = reject_user
    else:
        app.dependency_overrides[get_current_user] = lambda: current_user

    return TestClient(app, raise_server_exceptions=False)


def test_apply_uses_authenticated_user_and_preserves_workload_fields():
    db = FakeSession()
    user = SimpleNamespace(user_id=uuid4())
    agent = FakeAgent(
        estimate={
            "estimate_name": "AI capacity estimate",
            "cloud": "aws",
            "region": "us-west-2",
            "tier": "enterprise",
            # This legacy key caused Estimate construction to fail because the
            # ORM has no description column.
            "description": "Generated by the assistant",
        },
        workloads=[{
            "proposal_id": "proposal-1",
            "status": "pending",
            "workload_name": "Vector and AI services",
            "workload_type": "vector_search",
            "cloud": "aws",
            "vector_search_mode": "STORAGE_OPTIMIZED",
            "vector_capacity_millions": 64,
            "vector_search_storage_gb": 500,
            "fmapi_provider": "DATABRICKS",
            "fmapi_model": "databricks-meta-llama-3-1-70b-instruct",
            "fmapi_quantity": 1.25,
            "databricks_apps_size": "MEDIUM",
            "databricks_apps_num_apps": 2,
            "ai_parse_mode": "pages",
            "ai_parse_pages_thousands": 12.5,
            "driver_payment_option": "no_upfront",
        }],
    )
    chat_routes._conversation_agents["conversation-1"] = agent

    response = build_client(db, current_user=user).post(
        "/api/v1/chat/conversation-1/apply"
    )

    assert response.status_code == 200, response.text
    assert response.json()["workloads_created"] == 1
    assert db.commits == 1
    assert db.rollbacks == 0
    assert agent.reset_called is True

    estimate = next(record for record in db.added if isinstance(record, Estimate))
    line_item = next(record for record in db.added if isinstance(record, LineItem))

    assert estimate.owner_user_id == user.user_id
    assert estimate.cloud == "AWS"
    assert estimate.tier == "ENTERPRISE"
    assert line_item.estimate_id == estimate.estimate_id
    assert line_item.workload_type == "VECTOR_SEARCH"
    assert line_item.vector_search_mode == "storage_optimized"
    assert line_item.vector_capacity_millions == 64
    assert line_item.vector_search_storage_gb == 500
    assert line_item.fmapi_provider == "databricks"
    assert float(line_item.fmapi_quantity) == 1.25
    assert line_item.databricks_apps_num_apps == 2
    assert line_item.ai_parse_calculation_method == "pages_based"
    assert line_item.ai_parse_num_pages == 12500
    assert line_item.driver_payment_option == "no_upfront"
    assert not hasattr(line_item, "proposal_id")


def test_apply_returns_authentication_error_before_writing():
    db = FakeSession()
    chat_routes._conversation_agents["conversation-1"] = FakeAgent(
        estimate={"estimate_name": "Unauthorized"},
        workloads=[],
    )
    client = build_client(
        db,
        auth_error=HTTPException(status_code=401, detail="Not authenticated"),
    )

    response = client.post("/api/v1/chat/conversation-1/apply")

    assert response.status_code == 401
    assert db.added == []
    assert db.commits == 0
    assert db.rollbacks == 0


def test_apply_rejects_invalid_workload_and_rolls_back():
    db = FakeSession()
    agent = FakeAgent(
        estimate={"estimate_name": "Invalid workload"},
        workloads=[{"workload_type": "jobs"}],
    )
    chat_routes._conversation_agents["conversation-1"] = agent

    response = build_client(
        db,
        current_user=SimpleNamespace(user_id=uuid4()),
    ).post("/api/v1/chat/conversation-1/apply")

    assert response.status_code == 422
    assert db.commits == 0
    assert db.rollbacks == 1
    assert agent.reset_called is False
